# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npmVersionString=$(node -p "require('./src/Website/Template.Client/package.json').version") 
    echo "##vso[build.updatebuildnumber]$npmVersionString"
  displayName: 'Set build number'

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  workingDirectory: src/Website/Template.Client
  displayName: 'npm install and build'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: 'Publish unit test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage report'
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: false

#- task: CopyFiles@2
#  inputs:
#    SourceFolder: '$(Agent.BuildDirectory)/s/src/client/dist/template-website/'
#    Contents: '**'
#    TargetFolder: '$(Build.ArtifactStagingDirectory)'
#    CleanTargetFolder: true

#- task: S3Upload@1
#  inputs:
#    awsCredentials: 'AWS'
#    regionName: 'sa-east-1'
#    bucketName: 'template-webapi'
#    sourceFolder: '$(Build.ArtifactStagingDirectory)'
#    globExpressions: '**'
#    filesAcl: 'public-read'

#- task: Npm@1
#  displayName: 'Publish to feed'
#  inputs:
#    command: 'publish'
#    workingDir: 'components/ng-grid/'
#    publishRegistry: 'useFeed'
#    publishFeed: 'e7902e1c-f9a4-4aac-9ebb-dcc718fe7809'
